### ISSUE TITLE
Current state of this project?

### ISSUE THREAD

**Issue by kadixfox** [bekaertruben/ns-census-maximizer#3]
What is the current state of this project, as it has not been updated in over a year?
I do not currently know of any alternatives to this project's headless automated census-aware issue answering and am wondering if you plan to continue to improve this project.

**Comment by unshleepd** [comment]
For me everything works great and there are no issues lol. I justa added issues to skip myself into the script

**Comment by bekaertruben** [comment]
Hey, sorry for the late response. It's nice to hear that there are at least some people out there using my project :)
I have been wanting to revamp this project for a while to play around with some ML approaches.

For now, it should mostly be working in its current state, though I too added some extras to skip certain options and issues in my personalized script.

Of course, if either of you wants to get involved, I'd be happy to chat.

**Comment by bekaertruben** [comment]
@kadixfox @unshleepd
Finally got around to working on it a bit.
Reworked everything from the ground up, so there are doubtless still some kinks that will show up, but I've already solved about ~200 issues without any problems.

It's now a lot more modular, so you can implement your own outcome predictor and scoring algorithm.
Also wrote my own api wrapper, which throttles significantly less than the old pynationstates

**Comment by kadixfox** [comment]
This is fantastic! Very excited to play around with the modularity.

**Comment by bekaertruben** [comment]
> This is fantastic! Very excited to play around with the modularity.

If you encounter any issues, feel free to let met know
